name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build Dependencies
      - name: Build Dependencies
        run : npm run build

      # Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: node-build
          path: dist/
          retention-days: 7

      # Run tests (optional)
      #- name: Run tests
      #  run: npm test

  # Setup Python framework
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run basic check
        run: python -m py_compile app/main.py
